#!/usr/bin/env python
"""End-to-end harness that captures a real screenshot of the running React dashboard.

This intentionally exercises the *whole* real system rather than faking data:

1. Starts a local MQTT broker (``eclipse-mosquitto`` in Docker, same image
   the README's manual instructions use).
2. Starts the FastAPI dashboard (``uvicorn src.dashboard.api:app``),
   subscribed to that broker.
3. Runs the real analytics pipeline (real YOLOv8 CPU inference, the repo's
   own tracker, the repo's own zone-rule engine) against the demo video.
   As documented in ``scripts/generate_annotated_frames.py``, a
   COCO-pretrained detector produces no usable detections on that video's
   flat, untextured placeholder actors -- a real, expected result, not a
   bug -- so this step still proves the real ingest -> detect -> track ->
   zone-rule -> publish path runs end to end, it just doesn't by itself
   give the dashboard anything to display.
4. To still show the dashboard real data, replays the *same real YOLOv8
   detections* used for the "Detections" panel (Ultralytics' own bundled
   reference photos) through this repo's own tracker + zone engine +
   ``EventPublisher``, over the same MQTT broker -- real model inference,
   real ``VisionEvent`` objects (validated by the real pydantic schema),
   published over the real MQTT path the dashboard already subscribes to.
5. Builds the React frontend (picking up the annotated frames generated by
   ``scripts/generate_annotated_frames.py`` under ``frontend/public/screenshots/``)
   and serves the production build with ``vite preview``.
6. Uses Playwright (headless Chromium, via ``frontend/screenshot.mjs``) to
   open the running dashboard, wait for the live event table and detection
   images to actually render with real data, and save a full-page
   screenshot to ``docs/screenshots/dashboard.png``.
7. Tears everything down (processes + the mosquitto container).

Usage
-----
    python scripts/capture_dashboard_screenshot.py

Requires: Docker, Node/npm (with ``frontend``'s deps installed, including
the ``playwright`` devDependency + ``npx playwright install chromium`` run
at least once), and this repo's Python deps (``pip install -r
requirements.txt``) available on ``sys.executable``.
"""

from __future__ import annotations

import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRONTEND_DIR = REPO_ROOT / "frontend"
OUT_DIR = REPO_ROOT / "docs" / "screenshots"
SCREENSHOT_PATH = OUT_DIR / "dashboard.png"

MOSQUITTO_CONTAINER = "dashboard-screenshot-mosquitto"
# Non-default host ports: this machine may already have other projects'
# containers bound to 1883/8000 (a real risk on a shared dev box), so this
# harness picks ports unlikely to collide rather than assuming they're free.
MQTT_PORT = 18883
DASHBOARD_PORT = 8010
PREVIEW_PORT = 4173

PIPELINE_MAX_FRAMES = 200


def wait_for_port(host: str, port: int, timeout: float = 60.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=1.0):
                return True
        except OSError:
            time.sleep(0.5)
    return False


def wait_for_http_ok(url: str, timeout: float = 60.0) -> bool:
    import urllib.error
    import urllib.request

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2.0) as resp:  # noqa: S310
                if resp.status == 200:
                    return True
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(0.5)
    return False


def run(cmd: list[str] | str, cwd: Path = REPO_ROOT, **kwargs) -> subprocess.CompletedProcess:
    print(f"$ {cmd if isinstance(cmd, str) else ' '.join(cmd)}")
    return subprocess.run(cmd, cwd=cwd, shell=isinstance(cmd, str), **kwargs)


class ManagedProcess:
    """A background subprocess this script cleans up on exit."""

    def __init__(self, name: str, cmd: list[str] | str, cwd: Path, env: dict | None = None) -> None:
        self.name = name
        print(f"Starting {name}: {cmd if isinstance(cmd, str) else ' '.join(cmd)}")
        self.proc = subprocess.Popen(  # noqa: S603
            cmd,
            cwd=cwd,
            shell=isinstance(cmd, str),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            env=env,
        )

    def stop(self) -> None:
        if self.proc.poll() is None:
            print(f"Stopping {self.name} (pid={self.proc.pid})")
            self.proc.terminate()
            try:
                self.proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.proc.kill()


def publish_real_events_from_reference_photos(mqtt_port: int) -> int:
    """Real YOLOv8 detections -> real VisionEvents -> real MQTT publish.

    Reuses the exact detection/tracking/zone-rule logic in
    ``scripts/generate_annotated_frames.py`` (same bundled reference
    photos, same proportional zone/line scaling) so the dashboard has real,
    schema-validated events to render -- see this module's docstring for
    why the demo video itself doesn't produce any.
    """
    import cv2
    import yaml

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import generate_annotated_frames as gaf  # noqa: PLC0415

    from src.analytics.publisher import EventPublisher, PublisherConfig  # noqa: PLC0415
    from src.analytics.zones import ZoneRuleEngine  # noqa: PLC0415

    with open(REPO_ROOT / "config" / "pipeline.yaml", encoding="utf-8") as fh:
        config = yaml.safe_load(fh)
    zones_raw, lines_raw = gaf.load_overlay_geometry(REPO_ROOT / "config" / "pipeline.yaml")
    camera_id = config["camera"]["id"]

    from ultralytics.utils import ASSETS  # noqa: PLC0415

    detector = gaf.build_detector(config.get("detector", {}))
    publisher = EventPublisher(
        PublisherConfig(mqtt_host="localhost", mqtt_port=mqtt_port, mqtt_topic="analytics/events")
    )

    published = 0
    try:
        for image_path in sorted(Path(ASSETS).glob("*.jpg")):
            base_frame = cv2.imread(str(image_path))
            if base_frame is None:
                continue
            for frame in (base_frame, cv2.flip(base_frame, 1)):
                height, width = frame.shape[:2]
                scaled_zones, scaled_lines = gaf.scale_zones_and_lines(zones_raw, lines_raw, (width, height))
                tracker = gaf.build_tracker(config["tracker"])
                zone_engine = ZoneRuleEngine(*gaf._zones_lines_from_raw(scaled_zones, scaled_lines))

                detections = detector.detect(frame)
                tracked_objects = tracker.update(detections)
                from datetime import UTC, datetime  # noqa: PLC0415

                events = zone_engine.evaluate(camera_id, tracked_objects, datetime.now(UTC))
                for event in events:
                    publisher.publish(event)
                    published += 1
    finally:
        publisher.close()
    return published


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    docker_available = shutil.which("docker") is not None
    if not docker_available:
        print("ERROR: docker is required (to run a local mosquitto broker) but was not found on PATH.")
        sys.exit(1)

    managed: list[ManagedProcess] = []
    mosquitto_started = False

    try:
        # 1. MQTT broker ------------------------------------------------
        run(["docker", "rm", "-f", MOSQUITTO_CONTAINER], capture_output=True)
        result = run(
            [
                "docker", "run", "-d", "--rm",
                "--name", MOSQUITTO_CONTAINER,
                "-p", f"{MQTT_PORT}:1883",
                "eclipse-mosquitto:2",
                "mosquitto", "-c", "/mosquitto-no-auth.conf",
            ],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(result.stdout, result.stderr)
            raise RuntimeError("Failed to start mosquitto container")
        mosquitto_started = True
        if not wait_for_port("localhost", MQTT_PORT, timeout=30):
            raise RuntimeError("mosquitto broker did not come up on port 1883")
        print("mosquitto broker is up.")

        backend_env = {
            **__import__("os").environ,
            "MQTT_HOST": "localhost",
            "MQTT_PORT": str(MQTT_PORT),
            "MQTT_TOPIC": "analytics/events",
        }

        # 2. Dashboard (FastAPI) -----------------------------------------
        dashboard_proc = ManagedProcess(
            "dashboard (uvicorn)",
            [sys.executable, "-m", "uvicorn", "src.dashboard.api:app",
             "--host", "127.0.0.1", "--port", str(DASHBOARD_PORT)],
            cwd=REPO_ROOT,
            env=backend_env,
        )
        managed.append(dashboard_proc)
        if not wait_for_http_ok(f"http://127.0.0.1:{DASHBOARD_PORT}/health", timeout=30):
            raise RuntimeError("dashboard did not become healthy in time")
        print("dashboard is up.")

        # 3. Real analytics pipeline run (blocking) -----------------------
        print(
            f"Running analytics pipeline for up to {PIPELINE_MAX_FRAMES} frames "
            "(real YOLOv8 CPU inference)..."
        )
        pipeline_result = run(
            [sys.executable, "-m", "src.analytics.pipeline",
             "--config", "config/pipeline.yaml", "--max-frames", str(PIPELINE_MAX_FRAMES)],
            env=backend_env,
        )
        if pipeline_result.returncode != 0:
            raise RuntimeError("analytics pipeline run failed")

        # Give the dashboard's MQTT subscriber a moment to drain any
        # in-flight messages, then check whether real events landed.
        import json
        import urllib.request

        events: list = []
        for _ in range(6):
            with urllib.request.urlopen(f"http://127.0.0.1:{DASHBOARD_PORT}/events", timeout=5) as resp:  # noqa: S310
                events = json.loads(resp.read())
            if events:
                break
            time.sleep(1)
        print(f"Dashboard ring buffer has {len(events)} real event(s) after the demo-video pipeline run.")

        if not events:
            print(
                "As expected (see this module's + generate_annotated_frames.py's docstrings): "
                "a COCO-pretrained detector doesn't recognise the demo video's flat placeholder "
                "actors, so that run alone produced no events. Publishing real events derived "
                "from the same bundled reference-photo detections used for the Detections panel..."
            )
            n_published = publish_real_events_from_reference_photos(MQTT_PORT)
            print(f"Published {n_published} real VisionEvent(s) over MQTT.")
            for _ in range(10):
                with urllib.request.urlopen(f"http://127.0.0.1:{DASHBOARD_PORT}/events", timeout=5) as resp:  # noqa: S310
                    events = json.loads(resp.read())
                if events:
                    break
                time.sleep(1)
            print(f"Dashboard ring buffer now has {len(events)} real event(s).")

        # 4. Build + preview the frontend --------------------------------
        # vite.config.ts's dev/preview proxy defaults to localhost:8000, but
        # this harness runs the dashboard on DASHBOARD_PORT instead (to
        # avoid colliding with anything else already using 8000 on this
        # machine), so point it there via BACKEND_ORIGIN.
        import os as _os

        frontend_env = {**_os.environ, "BACKEND_ORIGIN": f"http://127.0.0.1:{DASHBOARD_PORT}"}

        npm = "npm.cmd" if sys.platform == "win32" else "npm"
        build_result = run([npm, "run", "build"], cwd=FRONTEND_DIR, env=frontend_env)
        if build_result.returncode != 0:
            raise RuntimeError("frontend build failed")

        preview_proc = ManagedProcess(
            "frontend (vite preview)",
            [npm, "run", "preview", "--", "--port", str(PREVIEW_PORT), "--strictPort"],
            cwd=FRONTEND_DIR,
            env=frontend_env,
        )
        managed.append(preview_proc)
        if not wait_for_http_ok(f"http://localhost:{PREVIEW_PORT}/", timeout=30):
            raise RuntimeError("vite preview did not come up in time")
        print("frontend preview server is up.")

        # 5. Screenshot with Playwright (Node) ----------------------------
        npx = "npx.cmd" if sys.platform == "win32" else "npx"
        shot_result = run(
            [npx, "playwright", "install", "chromium"],
            cwd=FRONTEND_DIR,
        )
        if shot_result.returncode != 0:
            print(
                "WARNING: `npx playwright install chromium` failed (likely no network "
                "access to download the browser binary in this environment). Falling "
                "back is not possible without a headless browser -- see the final "
                "report for what to do next."
            )
            raise RuntimeError("playwright chromium install failed")

        node = "node.exe" if sys.platform == "win32" else "node"
        node_result = run(
            [node, "screenshot.mjs", f"http://localhost:{PREVIEW_PORT}/", str(SCREENSHOT_PATH)],
            cwd=FRONTEND_DIR,
        )
        if node_result.returncode != 0:
            raise RuntimeError("playwright screenshot capture failed")

        print(f"Screenshot saved to {SCREENSHOT_PATH}")

    finally:
        for proc in reversed(managed):
            proc.stop()
        if mosquitto_started:
            run(["docker", "rm", "-f", MOSQUITTO_CONTAINER], capture_output=True)


if __name__ == "__main__":
    main()
